### ISSUE TITLE
vim screen becoming black

### ISSUE THREAD

**Issue by shreyanshjn** [clouduan/vim-searchme#2]
after typing \ss it searches the required text in the browser...but when i switch back to my vim...the entire screen becomes black..
![vimblack](https://user-images.githubusercontent.com/34000568/44526734-89e41700-a702-11e8-9186-fbaa39c5d99c.png)

**Comment by clouduan** [comment]
Which version are you using now?  
I just tested again on Neovim 0.3.0 with you [vimrc](https://github.com/shreyanshjn/dotfiles/blob/master/vim/vimrc). But I can not reproduce that issue...

**Comment by shreyanshjn** [comment]
I am using VIM- 7.4 @clouduan

**Comment by clouduan** [comment]
Actually I don't know what's wrong with this. But VIM-8.0 has release for a long time, it is stable and has a lot of new features especially async.  

There are also others new plugins only support VIM-8.0+ or Neovim.  So you may upgrading your VIM to version 8.0 and try it again. @shreyanshjn

**Comment by shreyanshjn** [comment]
upgrading vim also did not help.
